In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

## EX2. Randomly create a matrix of size (10, 5) then randomly assign values of 0 and 1 to the last column of this matrix.

In [4]:
import numpy as np

In [5]:
matrix = np.random.rand(10,5)
matrix[:,-1] = np.round(matrix[:,-1])
matrix

array([[0.08748063, 0.5643086 , 0.28559183, 0.98259297, 0.        ],
       [0.70246787, 0.16948569, 0.9486277 , 0.07411828, 0.        ],
       [0.81778737, 0.49039505, 0.15747588, 0.65712282, 0.        ],
       [0.22258361, 0.39533338, 0.1697712 , 0.99472562, 1.        ],
       [0.93804412, 0.84660258, 0.14487907, 0.72876176, 0.        ],
       [0.58585333, 0.9319862 , 0.95993081, 0.90662695, 0.        ],
       [0.01319656, 0.88482419, 0.35143891, 0.52635066, 0.        ],
       [0.68291478, 0.08264935, 0.33778009, 0.48386169, 0.        ],
       [0.81615933, 0.19830669, 0.71127716, 0.19023291, 0.        ],
       [0.91914542, 0.14747402, 0.12478961, 0.46511164, 0.        ]])

## Ex 3. Why we cannot use this index ? Please fix it !!

In [72]:
np_matrix = np.random.randint(11,size = (5,5))
np_matrix

array([[ 8,  1, 10,  4,  7],
       [ 4,  8,  3,  3,  8],
       [ 3,  8,  7,  0,  8],
       [ 8,  4,  4,  8,  0],
       [ 6,  2, 10, 10,  0]])

In [73]:
idx = [1,2,3,4,5]
np_matrix[idx,:]

IndexError: index 5 is out of bounds for axis 0 with size 5

### ANS ใช้indexนี้ไม่ได้ เพราะmatrixีค่าเป็น 4 นับจาก 0,1,2,3,4 จึงไม่สามารถใช้เลข5ได้

แก้โดย

In [76]:
idx = [0,1,2,3,4]
np_matrix[idx,:]

array([[ 8,  1, 10,  4,  7],
       [ 4,  8,  3,  3,  8],
       [ 3,  8,  7,  0,  8],
       [ 8,  4,  4,  8,  0],
       [ 6,  2, 10, 10,  0]])

## Ex 4. Randomly create a data matrix of 10 samples with 5 features. 
## Then, randomly create a label vector for 10 samples. 
## Finally, seperate samples into 2 groups
## Group 1 called train_data (label == 0)
## Group 2 called test_data (label == 1)

data_matrix

In [23]:
data_matrix = np.random.randint(10,size=(10,5))
data_matrix 

array([[0, 7, 2, 7, 2],
       [6, 8, 1, 5, 0],
       [3, 9, 8, 3, 7],
       [3, 0, 9, 4, 7],
       [7, 0, 4, 0, 1],
       [0, 6, 4, 0, 1],
       [8, 0, 4, 1, 5],
       [4, 9, 3, 5, 7],
       [4, 1, 2, 5, 7],
       [3, 3, 1, 5, 9]])

label_vector

In [25]:
label_vector = np.random.randint(2,size=10) 
label_vector

array([1, 1, 0, 0, 0, 0, 1, 1, 1, 1])

train_data

In [28]:
data_matrix[np.where(label_vector == 0)]

array([[3, 9, 8, 3, 7],
       [3, 0, 9, 4, 7],
       [7, 0, 4, 0, 1],
       [0, 6, 4, 0, 1]])

test_data

In [29]:
data_matrix[np.where(label_vector == 1)]

array([[0, 7, 2, 7, 2],
       [6, 8, 1, 5, 0],
       [8, 0, 4, 1, 5],
       [4, 9, 3, 5, 7],
       [4, 1, 2, 5, 7],
       [3, 3, 1, 5, 9]])